# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\@@政大資訊科學在職\1-4-人工智慧\掃地機器人\GUI\AI_GUI_1071129.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 688)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Map = QtWidgets.QGraphicsView(self.centralwidget)
        self.Map.setGeometry(QtCore.QRect(20, 50, 661, 471))
        self.Map.setObjectName("Map")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 20, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(700, 50, 297, 585))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Range = QtWidgets.QLabel(self.formLayoutWidget)
        self.Range.setText("")
        self.Range.setObjectName("Range")
        self.verticalLayout_2.addWidget(self.Range)
        self.CleanTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.CleanTime.setText("")
        self.CleanTime.setObjectName("CleanTime")
        self.verticalLayout_2.addWidget(self.CleanTime)
        self.Area = QtWidgets.QLabel(self.formLayoutWidget)
        self.Area.setText("")
        self.Area.setObjectName("Area")
        self.verticalLayout_2.addWidget(self.Area)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.Electricity = QtWidgets.QLabel(self.formLayoutWidget)
        self.Electricity.setObjectName("Electricity")
        self.verticalLayout_2.addWidget(self.Electricity)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.dateTimeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(2018, 12, 1))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dateTimeEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.pushButton_7 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_7.setMouseTracking(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.formLayout_4.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.listView = QtWidgets.QListView(self.formLayoutWidget)
        self.listView.setObjectName("listView")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.listView)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 20, 271, 22))
        self.comboBox.setObjectName("comboBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 540, 413, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 1, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 7, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 1, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 1, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 6, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 1, 5, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 1, 4, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(440, 540, 252, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_17.setBuddy(self.lineEdit_16)
        self.label_14.setBuddy(self.lineEdit_13)
        self.label_15.setBuddy(self.lineEdit_14)
        self.label_13.setBuddy(self.lineEdit_12)
        self.label_12.setBuddy(self.lineEdit_11)
        self.label_16.setBuddy(self.lineEdit_15)

        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(MainWindow.update)
        self.pushButton.clicked.connect(self.listView.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Map, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.dateTimeEdit)
        MainWindow.setTabOrder(self.dateTimeEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.lineEdit_16)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "輸入地圖"))
        self.pushButton_2.setText(_translate("MainWindow", "確定"))
        self.label_5.setText(_translate("MainWindow", "移動距離"))
        self.label_4.setText(_translate("MainWindow", "清理時間"))
        self.label_6.setText(_translate("MainWindow", "掃地面積??"))
        self.label.setText(_translate("MainWindow", "執行掃地次數"))
        self.label_7.setText(_translate("MainWindow", "目前電量"))
        self.label_3.setText(_translate("MainWindow", "達成率"))
        self.label_2.setText(_translate("MainWindow", "清潔率"))
        self.label_23.setText(_translate("MainWindow", "123"))
        self.Electricity.setText(_translate("MainWindow", "123"))
        self.label_20.setText(_translate("MainWindow", "123"))
        self.label_25.setText(_translate("MainWindow", "123"))
        self.label_10.setText(_translate("MainWindow", "預約清掃"))
        self.pushButton.setText(_translate("MainWindow", "ADD"))
        self.label_11.setText(_translate("MainWindow", "禁區設置"))
        self.pushButton_7.setText(_translate("MainWindow", "掃這裡"))
        self.pushButton_8.setText(_translate("MainWindow", "不掃這裡"))
        self.label_9.setText(_translate("MainWindow", "遠程遙控"))
        self.pushButton_3.setText(_translate("MainWindow", "UP"))
        self.pushButton_4.setText(_translate("MainWindow", "LEFT"))
        self.pushButton_5.setText(_translate("MainWindow", "DOWN"))
        self.pushButton_6.setText(_translate("MainWindow", "RIGHT"))
        self.label_17.setText(_translate("MainWindow", "&c"))
        self.label_14.setText(_translate("MainWindow", "&z"))
        self.label_15.setText(_translate("MainWindow", "&a"))
        self.label_13.setText(_translate("MainWindow", "&y"))
        self.label_12.setText(_translate("MainWindow", "&x"))
        self.label_16.setText(_translate("MainWindow", "&b"))
        self.pushButton_9.setText(_translate("MainWindow", "更新狀態"))
        self.label_18.setText(_translate("MainWindow", "目前時間"))

